<?php

namespace Proxies\__CG__\svplocation\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \svplocation\AdminBundle\Entity\Commande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'idCmd', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'idBeneficiaire', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'projet', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'typeCmd', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'dateReservation', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'dateRetour', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'description', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'statut');
        }

        return array('__isInitialized__', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'idCmd', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'idBeneficiaire', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'projet', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'typeCmd', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'dateReservation', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'dateRetour', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'description', '' . "\0" . 'svplocation\\AdminBundle\\Entity\\Commande' . "\0" . 'statut');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCmd()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCmd();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCmd', array());

        return parent::getIdCmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBeneficiaire($idBeneficiaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBeneficiaire', array($idBeneficiaire));

        return parent::setIdBeneficiaire($idBeneficiaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdBeneficiaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBeneficiaire', array());

        return parent::getIdBeneficiaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjet($projet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjet', array($projet));

        return parent::setProjet($projet);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjet', array());

        return parent::getProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeCmd($typeCmd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeCmd', array($typeCmd));

        return parent::setTypeCmd($typeCmd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeCmd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeCmd', array());

        return parent::getTypeCmd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateReservation($dateReservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateReservation', array($dateReservation));

        return parent::setDateReservation($dateReservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateReservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateReservation', array());

        return parent::getDateReservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateRetour($dateRetour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRetour', array($dateRetour));

        return parent::setDateRetour($dateRetour);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRetour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRetour', array());

        return parent::getDateRetour();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', array($statut));

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', array());

        return parent::getStatut();
    }

}
